# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d57d07a35810cdfa3447e8e743fa391b1865c0f72f2318249e4514799feb122ee83d0f400864128ac83c72c1581daf166783d84554756fe083089f1e88fe8ff

test:
  secret_key_base: 05c0468215591904eb6068489b164746cb66f104cf91a73a86ffada1cdd65b0621066b0da265043dc60fd7fc4592c8cb8708a349198841fcdf1e13436c2cd61e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
